import type { Metadata } from "next";
import { siteUrl } from "@/lib/site-url";

// Single source of truth for the public origin and the default SEO copy.
//
// The origin itself is resolved by site-url.ts (NEXT_PUBLIC_SITE_URL →
// NEXTAUTH_URL → vercel.app fallback). Production sets
// NEXT_PUBLIC_SITE_URL=https://insulin-reset.bg — the apex is canonical and
// www / the vercel.app alias 308 to it (Vercel domain setting + next.config).
export const SITE_URL = siteUrl();

export const SITE_NAME = "InsulinReset";

// The lay term people actually search for ("инсулинова резистентност") lives
// in the title. The same line is the tagline on the OG share card
// (scripts/gen-og-image.mjs) — keep the two in sync.
export const SITE_TAGLINE = "90-дневен протокол за инсулинова резистентност";

export const SITE_TITLE = `${SITE_NAME} — ${SITE_TAGLINE}`;

export const SITE_DESCRIPTION =
  "90-дневен протокол за обръщане на инсулиновата резистентност по д-р Benjamin Bikman: дневен план, HOMA-IR, инсулин на гладно, храни, гладуване и CGM. Безплатно.";

// Static 1200×630 card generated by `npm run og:gen`. Resolves against
// metadataBase, so it ships as an absolute URL.
export const OG_IMAGE = {
  url: "/og-image.png",
  width: 1200,
  height: 630,
  alt: SITE_TITLE,
};

export function absoluteUrl(path = "/"): string {
  return `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`;
}

interface PageMetadataInput {
  /** Plain string gets the layout's "%s — InsulinReset" template; pass
   *  `{ absolute }` (the landing page) to opt out of the template. */
  title: string | { absolute: string };
  description: string;
  /** Path relative to the site root, e.g. "/foods". Used for canonical + og:url. */
  path: string;
}

// Metadata for a publicly indexable page: its own canonical URL, explicit
// index/follow, and Open Graph / Twitter copy for *this* page. Next merges
// metadata shallowly per top-level key, so openGraph must be complete here —
// otherwise a page would drop the layout's images/locale/siteName.
export function pageMetadata({ title, description, path }: PageMetadataInput): Metadata {
  return {
    title,
    description,
    alternates: { canonical: path },
    robots: { index: true, follow: true },
    openGraph: {
      type: "website",
      locale: "bg_BG",
      siteName: SITE_NAME,
      url: path,
      description,
      images: [OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      description,
      images: [OG_IMAGE.url],
    },
  };
}

// Metadata for pages that must stay out of search results: user-data
// dashboards that render an empty shell for crawlers, the onboarding funnel
// and the print view. `follow: true` keeps internal link equity flowing.
export function privateMetadata(title?: string): Metadata {
  return {
    ...(title ? { title } : {}),
    robots: { index: false, follow: true },
  };
}
