import type { Metadata, Viewport } from "next";
import { Montserrat, Nunito_Sans } from "next/font/google";
import "./globals.css";
import SessionProvider from "@/components/SessionProvider";
import AuthBadge from "@/components/AuthBadge";
import SyncOnLogin from "@/components/SyncOnLogin";
import MigrateLocalData from "@/components/MigrateLocalData";
import Toast from "@/components/Toast";
import GlobalFooter from "@/components/GlobalFooter";
import SkipLink from "@/components/SkipLink";
import AppShell from "@/components/AppShell";
import RegisterServiceWorker from "@/components/RegisterServiceWorker";
import JsonLd from "@/components/JsonLd";
import { OG_IMAGE, SITE_DESCRIPTION, SITE_NAME, SITE_TITLE, SITE_URL } from "@/lib/site";

// Self-hosted variable fonts via next/font (replaces the Google Fonts
// @import in globals.css, which was a ~2 s render-blocking chain on the
// landing page). Exposed as CSS variables; globals.css maps them onto the
// --font-heading / --font-body design tokens.
const montserrat = Montserrat({
  subsets: ["latin", "cyrillic"],
  display: "swap",
  variable: "--font-montserrat",
});

const nunitoSans = Nunito_Sans({
  subsets: ["latin", "cyrillic"],
  display: "swap",
  variable: "--font-nunito-sans",
});

// Site-wide defaults only. Each page owns its canonical URL, robots policy
// and Open Graph copy through pageMetadata() / privateMetadata() in
// src/lib/site.ts — never add `alternates.canonical` here: Next inherits it
// into every nested page, which told Google all pages were the homepage.
export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: SITE_TITLE,
    template: `%s — ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  category: "health",
  // No og/twitter title, url or description here: they fall back to each
  // page's resolved <title> / description, so every page shares correctly.
  openGraph: {
    type: "website",
    locale: "bg_BG",
    siteName: SITE_NAME,
    images: [OG_IMAGE],
  },
  twitter: {
    card: "summary_large_image",
    images: [OG_IMAGE.url],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: SITE_NAME,
  },
  icons: {
    // iOS Safari rejects SVG for apple-touch-icon; without the PNG it
    // falls back to a page screenshot. Generated by scripts/rasterize-icons.mjs.
    apple: { url: "/apple-icon-180.png", sizes: "180x180", type: "image/png" },
  },
  // Google Search Console ownership (URL-prefix property https://insulin-reset.bg/).
  // Keep it: removing the tag un-verifies the property.
  // public/googled0e6f48913f6dd21.html is the HTML-file variant of the same check.
  verification: {
    google: "3bPJeY0HkLUobwkqOM-OVZu6o5cKpMy3ktL3UFKh_PI",
  },
};

export const viewport: Viewport = {
  themeColor: "#1B7A6E",
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="bg" className={`${montserrat.variable} ${nunitoSans.variable}`}>
      <body className="flex min-h-dvh flex-col antialiased">
        <JsonLd />
        <SessionProvider>
          <RegisterServiceWorker />
          <SkipLink />
          <SyncOnLogin />
          <MigrateLocalData />
          <AuthBadge />
          {/* AppShell adds the desktop sidebar + mobile bottom-tab nav for
              app routes, and renders bare (no chrome) on marketing / funnel /
              print routes. The #main-content landmark (SkipLink target;
              tabIndex=-1 = programmatic focus only) and footer live inside it
              so the shell can offset them for the sidebar + bottom bar. */}
          <AppShell>
            <div id="main-content" tabIndex={-1} className="flex-1 outline-none">
              {children}
            </div>
            <GlobalFooter />
          </AppShell>
          <Toast />
        </SessionProvider>
      </body>
    </html>
  );
}
