import type { Metadata, Viewport } from "next";
import "./globals.css";
import SessionProvider from "@/components/SessionProvider";
import AuthBadge from "@/components/AuthBadge";
import SyncOnLogin from "@/components/SyncOnLogin";
import Toast from "@/components/Toast";
import GlobalFooter from "@/components/GlobalFooter";
import { siteUrl } from "@/lib/site-url";

const SITE_URL = siteUrl();

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  alternates: {
    // Canonical URL hint — keeps Google from indexing
    // insulin-resistance-app.vercel.app once a custom domain is set
    // (just update NEXT_PUBLIC_SITE_URL and it follows).
    canonical: "/",
  },
  title: "InsulinReset — 90-дневен протокол",
  description:
    "InsulinReset — 90-дневно обръщане на инсулиновата резистентност, базирано на работата на д-р Benjamin Bikman.",
  openGraph: {
    type: "website",
    locale: "bg_BG",
    url: SITE_URL,
    siteName: "InsulinReset",
    title: "InsulinReset — 90-дневен протокол",
    description:
      "Свали инсулина си преди да стане диабет. 90-дневен научно обоснован протокол по д-р Benjamin Bikman.",
    // The PNG is generated from app/opengraph-image.tsx — Next injects it
    // automatically, but we declare locale/site name here for completeness.
  },
  twitter: {
    card: "summary_large_image",
    title: "InsulinReset — 90-дневен протокол",
    description:
      "Свали инсулина си преди да стане диабет. 90-дневен научно обоснован протокол по д-р Benjamin Bikman.",
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "InsulinReset",
  },
  icons: {
    // iOS Safari rejects SVG for apple-touch-icon; without the PNG it
    // falls back to a page screenshot. Generated by scripts/rasterize-icons.mjs.
    apple: { url: "/apple-icon-180.png", sizes: "180x180", type: "image/png" },
  },
};

export const viewport: Viewport = {
  themeColor: "#1B7A6E",
  width: "device-width",
  initialScale: 1,
};

// JSON-LD MedicalWebPage schema — helps Google understand the site is a
// medical educational resource (not a product / shop). Conservative
// claims only, with the "based on" attribution to Bikman's published work.
const jsonLd = {
  "@context": "https://schema.org",
  "@type": "MedicalWebPage",
  name: "InsulinReset",
  url: SITE_URL,
  inLanguage: "bg-BG",
  about: {
    "@type": "MedicalCondition",
    name: "Insulin resistance",
    alternateName: "Инсулинова резистентност",
  },
  audience: {
    "@type": "MedicalAudience",
    audienceType: "Patient",
  },
  citation: {
    "@type": "Book",
    name: "Why We Get Sick",
    author: { "@type": "Person", name: "Benjamin Bikman, PhD" },
  },
  publisher: {
    "@type": "Organization",
    name: "InsulinReset",
    url: SITE_URL,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="bg">
      <body className="flex min-h-dvh flex-col antialiased">
        <script
          type="application/ld+json"
          // schema.org JSON-LD — safe; static content from a constant above.
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <SessionProvider>
          <SyncOnLogin />
          <AuthBadge />
          <div className="flex-1">{children}</div>
          <GlobalFooter />
          <Toast />
        </SessionProvider>
      </body>
    </html>
  );
}
