import type { MetadataRoute } from "next";

// PWA manifest — makes the app installable to home screen on supported
// platforms. Both SVG (modern Android Chrome / desktop installs) and PNG
// (older targets + iOS install prompts) are listed. PNGs are generated by
// `scripts/rasterize-icons.mjs` from src/app/icon.svg.

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "InsulinReset — 90-дневен протокол",
    short_name: "InsulinReset",
    description:
      "InsulinReset — 90-дневно обръщане на инсулиновата резистентност, базирано на работата на д-р Benjamin Bikman.",
    start_url: "/",
    display: "standalone",
    background_color: "#F0FAF6",
    theme_color: "#1B7A6E",
    lang: "bg",
    icons: [
      {
        src: "/icon.svg",
        sizes: "any",
        type: "image/svg+xml",
        purpose: "any",
      },
      {
        src: "/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/apple-icon-180.png",
        sizes: "180x180",
        type: "image/png",
        purpose: "any",
      },
    ],
  };
}
